In [2]:
import numpy as np

In [3]:
#Q1
array_10_zeros = np.zeros(10)
print(array_10_zeros)

array_10_ones = np.ones(10)
print(array_10_ones)


array_10_fives = np.full(10, 5)
print(array_10_fives)





[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [4]:
#Q2
array_even_numbers = np.arange(30, 71, 2)
print(array_even_numbers)



[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [5]:
#Q3
array_30_zeros = np.zeros((5,6))
print(array_30_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [6]:
#Q4
array_10_10_random_numbers = np.random.random(size=(10, 10))
print(array_10_10_random_numbers)
print(f"Max: {array_10_10_random_numbers.max()}")
print(f"Min: {array_10_10_random_numbers.min()}")
print(f"Max: {np.max(array_10_10_random_numbers)}")
print(f"Min: {np.min(array_10_10_random_numbers)}")


[[0.61402383 0.62470203 0.04654182 0.25997439 0.12829779 0.19480961
  0.56758767 0.86745501 0.82897019 0.21877209]
 [0.54442803 0.34873072 0.4815961  0.13253598 0.47814933 0.64914138
  0.27860493 0.78610024 0.88469156 0.50160463]
 [0.7333733  0.67431837 0.76514652 0.91233766 0.34993634 0.97649045
  0.87318944 0.18133035 0.83702307 0.45043197]
 [0.60733497 0.93438462 0.41959801 0.64928211 0.37727922 0.73111433
  0.83702241 0.32394591 0.57421977 0.25893816]
 [0.8461627  0.90626933 0.49639311 0.91476803 0.95270641 0.0331402
  0.48210418 0.84328448 0.92836928 0.011134  ]
 [0.668557   0.8184929  0.90650005 0.85722114 0.26297827 0.58684394
  0.44562225 0.02640899 0.7696588  0.23621703]
 [0.30755611 0.78183887 0.64881769 0.17877164 0.08154918 0.4395355
  0.5676246  0.22689111 0.44831726 0.53619894]
 [0.63882423 0.56341597 0.22839081 0.47553462 0.34063064 0.48902866
  0.36201466 0.80330819 0.63096935 0.74102449]
 [0.51475728 0.57344703 0.80753626 0.32866256 0.20759158 0.59462922
  0.26059912 0

In [7]:
#Q5
array_3_3_random_numbers = np.random.randint(2, 10, size=(3, 3))
print(array_3_3_random_numbers)


[[5 7 5]
 [2 7 4]
 [2 8 9]]


In [8]:
#Q6
array_20 = np.arange(20)
print(array_20)
print(array_20[array_20>15])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[16 17 18 19]


In [9]:
#Q7
array_1 = np.array([[0, 1, 3]
                    , [5, 7, 9]])
array_2 = np.array([[0, 2, 4]
                    , [6, 8, 10]])
array_horizontal = np.hstack((array_1, array_2))
print(array_horizontal)
array_vertical = np.vstack((array_1, array_2))
print(array_vertical)


[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]


In [10]:
#Q8
array_10_ones = np.ones(10)
print(array_10_ones)
array_10_ones[5] = 11
print(array_10_ones)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1.  1.  1.  1.  1. 11.  1.  1.  1.  1.]


In [11]:
#Q9
array_10_ones = np.append(array_10_ones, 11)
print(array_10_ones)



[ 1.  1.  1.  1.  1. 11.  1.  1.  1.  1. 11.]


In [12]:
#Q10
array_10 = np.arange(10)
print(array_10)
array_10 = array_10 [::-1]
print(array_10)
array_10 = np.flip(array_10)
print(array_10)
array_10 = np.array(list(reversed(array_10)))
print(array_10)




[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
