In [1]:
import numpy as np

In [2]:
#Q1
array_10_zeros = np.zeros(10)
print(array_10_zeros)

array_10_ones = np.ones(10)
print(array_10_ones)


array_10_fives = np.full(10, 5)
print(array_10_fives)





[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [3]:
#Q2
array_even_numbers = np.arange(30, 71, 2)
print(array_even_numbers)



[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [4]:
#Q3
array_30_zeros = np.zeros((5,6))
print(array_30_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [5]:
#Q4
array_10_10_random_numbers = np.random.random(size=(10, 10))
print(array_10_10_random_numbers)
print(f"Max: {array_10_10_random_numbers.max()}")
print(f"Min: {array_10_10_random_numbers.min()}")
print(f"Max: {np.max(array_10_10_random_numbers)}")
print(f"Min: {np.min(array_10_10_random_numbers)}")


[[0.55565919 0.21382653 0.58422585 0.84573711 0.14871461 0.24209275
  0.33280945 0.4135666  0.22689208 0.93762492]
 [0.99831599 0.31787231 0.5279069  0.87839936 0.86324747 0.64090591
  0.90498133 0.98439309 0.67064566 0.07411008]
 [0.69273902 0.52493507 0.43651321 0.71245985 0.43008303 0.5843432
  0.31108235 0.2184437  0.8898951  0.15439053]
 [0.73921118 0.62625362 0.43354275 0.90677315 0.73162447 0.04869476
  0.21161403 0.33957928 0.03825071 0.4601924 ]
 [0.42912888 0.52655773 0.94182848 0.7311113  0.28420948 0.05826876
  0.50849995 0.33895435 0.72157099 0.88907273]
 [0.49094034 0.99091444 0.07845815 0.03221241 0.51234319 0.68673529
  0.43276624 0.05225795 0.64860674 0.80060935]
 [0.51880175 0.96644408 0.47883261 0.82880519 0.73509792 0.98274444
  0.92715641 0.08700223 0.26704527 0.3673103 ]
 [0.86216722 0.2843423  0.13840466 0.97032749 0.52436717 0.68145609
  0.82503265 0.28427603 0.0229732  0.13142464]
 [0.5928757  0.36015234 0.4061417  0.28151611 0.17590652 0.56080475
  0.9571037  

In [6]:
#Q5
array_3_3_random_numbers = np.random.randint(2, 10, size=(3, 3))
print(array_3_3_random_numbers)


[[8 4 4]
 [6 9 5]
 [5 3 7]]


In [7]:
#Q6
array_20 = np.arange(20)
print(array_20)
print(array_20[array_20>15])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[16 17 18 19]


In [8]:
#Q7
array_1 = np.array([[0, 1, 3]
                    , [5, 7, 9]])
array_2 = np.array([[0, 2, 4]
                    , [6, 8, 10]])
array_horizontal = np.hstack((array_1, array_2))
print(array_horizontal)
array_vertical = np.vstack((array_1, array_2))
print(array_vertical)


[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]


In [9]:
#Q8
array_10_ones = np.ones(10)
print(array_10_ones)
array_10_ones[5] = 11
print(array_10_ones)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1.  1.  1.  1.  1. 11.  1.  1.  1.  1.]


In [10]:
#Q9
array_10_ones = np.append(array_10_ones, 11)
print(array_10_ones)



[ 1.  1.  1.  1.  1. 11.  1.  1.  1.  1. 11.]


In [11]:
#Q10
array_10 = np.arange(10)
print(array_10)
array_10 = array_10 [::-1]
print(array_10)
array_10 = np.flip(array_10)
print(array_10)
array_10 = np.array(list(reversed(array_10)))
print(array_10)




[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
